version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: auth-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth

volumes:
  mongodb_data: